
env: &env prod

configmap:

secrets:

# This will use the default deployment strategy unless it is overridden
deploymentStrategy: { }

# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube.
resources:
  requests:
    cpu: 2000m
    memory: 2Gi
  limits:
    cpu: 2000m
    memory: 2Gi

hpa:
  minReplicas: 1
  maxReplicas: 5
  averageUtilization: 70

ingress:
  partnering:
    hosts:
      - lightweight-app
