apiVersion: apps/v1
kind: Deployment
metadata:
  name: lightweight-app
  labels:
    app: lightweight-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lightweight-app
  template:
    metadata:
      labels:
        app: lightweight-app
    spec:
      containers:
      - name: lightweight-app
        image: 967763538108.dkr.ecr.eu-central-1.amazonaws.com/app.1.18.203-release_branch_R1.18
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: lightweight-app
spec:
  selector:
    app: lightweight-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

